CREATE TABLE exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    weight INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    workout_date DATE NOT NULL,
    CONSTRAINT uk_exercise_name UNIQUE (name),
    CONSTRAINT ck_exercise_weight CHECK (weight >= 0),
    CONSTRAINT ck_exercise_reps CHECK (reps > 0)
);

CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_day VARCHAR(80) NOT NULL,
    muscle_group VARCHAR(160) NOT NULL
);

CREATE TABLE schedule_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    CONSTRAINT fk_schedule_item_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (id) ON DELETE CASCADE,
    CONSTRAINT fk_schedule_item_exercise FOREIGN KEY (exercise_id) REFERENCES exercises (id) ON DELETE CASCADE,
    CONSTRAINT uk_schedule_exercise UNIQUE (schedule_id, exercise_id)
);

CREATE TABLE workout_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_name VARCHAR(120) NOT NULL,
    weight INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    workout_date DATE NOT NULL,
    CONSTRAINT ck_history_weight CHECK (weight >= 0),
    CONSTRAINT ck_history_reps CHECK (reps > 0)
);

CREATE INDEX idx_history_exercise_date ON workout_history (exercise_name, workout_date, id);
CREATE INDEX idx_schedule_exercise_schedule ON schedule_exercises (schedule_id, id);
