CREATE TABLE nutrition_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date DATE NOT NULL,
    meal_type VARCHAR(40) NOT NULL,
    food_name VARCHAR(160) NOT NULL,
    calories INTEGER NOT NULL,
    protein INTEGER NOT NULL,
    carbs INTEGER NOT NULL,
    fat INTEGER NOT NULL,
    notes VARCHAR(400),
    CONSTRAINT ck_nutrition_values CHECK (calories >= 0 AND protein >= 0 AND carbs >= 0 AND fat >= 0)
);

CREATE TABLE milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(140) NOT NULL,
    milestone_date DATE NOT NULL,
    description VARCHAR(600),
    image_name VARCHAR(180) NOT NULL,
    image_type VARCHAR(80) NOT NULL,
    image_data BYTEA NOT NULL
);

CREATE INDEX idx_nutrition_date ON nutrition_entries (entry_date, id);
CREATE INDEX idx_milestone_date ON milestones (milestone_date, id);
